import pyautogui
import pandas
import time
ed=pandas.read_excel('Data1.xlsx')
count =0
time.sleep(2)
pyautogui.press("win")
time.sleep(3)
pyautogui.write("Google")
time.sleep(2)
pyautogui.press("enter")
time.sleep(2)
pyautogui.press('tab')
time.sleep(1)
print("one")
pyautogui.press('tab')
time.sleep(1)
print("two")
pyautogui.press('tab')
time.sleep(1)
print("three")
pyautogui.press('tab')
time.sleep(1)
print("four")
pyautogui.press('enter')
time.sleep(1)
ro=ed["ROW ID"].fillna('')
lr=list(ro)
nme=ed["NAME:"].fillna('')
l1=list(nme)
clg=ed["COLLEGE NAME:"].fillna('')
l2=list(clg)
phn=ed["PHONE NO:"].fillna('')
phn1=phn.values
l3=list(phn1)
l3s=[str(x) for x in l3]
dept=ed["DEPARTMENT:"].fillna('')
l4=list(dept)
cou=ed["COURSE:"].fillna('')
l5=list(cou)
dur=ed["DURATION :"].fillna('')
l6=list(dur)
fee=ed["FEE:"].fillna('')
l7=list(fee)
fee1=fee.values
l7=list(fee1)
l7s=[str(y) for y in l7]
paym=ed["PAYMENT MODE:"].fillna('')
l8=list(paym)
gmail=ed["Gmail ID:"].fillna('')
l9=list(gmail)

def search(r,n,c,p,d,co,du,f,pay,g):
    for i in range(len(r)):
        pyautogui.hotkey('ctrl', 't')
        pyautogui.doubleClick(x=289,y=66,button="left")
        pyautogui.write("http://localhost/xampp/subhiksha/intern1.html")
        pyautogui.press('enter')
        time.sleep(1)
        pyautogui.press('tab')
        time.sleep(1)
        time.sleep(2)
        pyautogui.write(n[i])
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.write(c[i])
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.write(p[i])
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.write(d[i])
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.write(co[i])
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.write(du[i])
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.write(f[i])
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.write(pay[i])
        pyautogui.press('tab')
        time.sleep(1)
        pyautogui.write(g[i])
        time.sleep(1)
        pyautogui.press('enter')
        time.sleep(1)        
search(lr,l1,l2,l3s,l4,l5,l6,l7s,l8,l9)

